package strategicGame;

public class grid {

	
	[
	IMPASSABLE,IMPASSABLE,IMPASSABLE,IMPASSABLE,IMPASSABLE,IMPASSABLE,IMPASSABLE,IMPASSABLE,IMPASSABLE,IMPASSABLE
	IMPASSABLE,PLAYER,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,IMPASSABLE
	IMPASSABLE,EMPTY,IMPASSABLE,EMPTY,IMPASSABLE,IMPASSABLE,EMPTY,IMPASSABLE,EMPTY,IMPASSABLE
	IMPASSABLE,EMPTY,IMPASSABLE,EMPTY,IMPASSABLE,IMPASSABLE,EMPTY,IMPASSABLE,EMPTY,IMPASSABLE
	IMPASSABLE,EMPTY,IMPASSABLE,EMPTY,EMPTY,EMPTY,EMPTY,IMPASSABLE,EMPTY,IMPASSABLE
	IMPASSABLE,EMPTY,EMPTY,EMPTY,IMPASSABLE,IMPASSABLE,EMPTY,EMPTY,EMPTY,IMPASSABLE
	IMPASSABLE,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,IMPASSABLE
	IMPASSABLE,EMPTY,IMPASSABLE,IMPASSABLE,EMPTY,EMPTY,IMPASSABLE,IMPASSABLE,EMPTY,IMPASSABLE
	IMPASSABLE,MONSTER,EMPTY,EMPTY,MONSTER,EMPTY,EMPTY,EMPTY,EMPTY,IMPASSABLE
	IMPASSABLE,IMPASSABLE,IMPASSABLE,IMPASSABLE,IMPASSABLE,IMPASSABLE,IMPASSABLE,IMPASSABLE,IMPASSABLE,IMPASSABLE
	]
	
	
}
